#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

HOST_UID="$(id -u)"
HOST_GID="$(id -g)"

cat > "${ENV_FILE}" <<EOF
# Auto-generated by .devcontainer/init-uid-gid.sh
# ホストユーザーの UID/GID。compose.yaml の build args で使用されます。
HOST_UID=${HOST_UID}
HOST_GID=${HOST_GID}
EOF

echo "Wrote HOST_UID=${HOST_UID}, HOST_GID=${HOST_GID} to ${ENV_FILE}"
